### ISSUE TITLE
[Form Elements] Have class for 100% form field width

### ISSUE THREAD

**Issue by bambattajb** [standrewsdigital/digital-pattern-library#169]
A site we're working on has a small enquiry form in the sidebar. It would be useful to have a class that allows the form fields to use 100% of the container width. 

![screenshot from 2017-02-21 14-21-34](https://cloud.githubusercontent.com/assets/480898/23168727/0ff2f09a-f841-11e6-8347-e1565bb740a9.png)

100% width is applied when wrapping the field in .input-group and using .input-group-addon

Ref - http://discoverstandrews-dev.wftest.co.uk/wp-content/themes/discoverstandrews/digital-pattern-library/docs/patterns/form-elements/index.html

**Comment by Aarontlott** [comment]
We can now use bootstrap col-md-* to change the sizing of the form elements, thanks for your input.
