### ISSUE TITLE
FEAT (Staff listing) Create HTML and CSS for staff listing pattern in DPL

### ISSUE THREAD

**Issue by garethjmsaunders** [standrewsdigital/digital-pattern-library#3]
* Organise the staff profiles in an easy to consume, easy to navigate way.
* Be as usable on mobile as it is on desktop
* Convey relevant data to the end users
* Work cross browser

## Branch

`lw75-staff-listings`

## Acceptance criteria

* Code is responsive
* HTML code well formed
* CSS code well formed

---

Responsible: Lewis
Tester: Aaron

**Comment by Aarontlott** [comment]
This is ready except there is a weird bug in the DPL that shows the cards with a larger height than expected and it is ignoring all CSS and attempts to adjust it. I think this is related to the iframe that pulls in the card pattern.

**Comment by Aarontlott** [comment]
I need to fix the bug in the height before I can merge this.

**Comment by Aarontlott** [comment]
Bug is fixed, turns out it was a CSS conflict with the contact-card class. Fixed.
