### ISSUE TITLE
FIX (Navbox) Titles overrunning boxes on mobile devices

### ISSUE THREAD

**Issue by garethjmsaunders** [standrewsdigital/digital-pattern-library#4]
https://www.st-andrews.ac.uk/students/robert-jones-scholarship-programme/

When using mobile devices to view navboxes, if the title is too long then the text overruns the box. The solution may be to reduce the font size for certain breakpoints? 

## Acceptance criteria

* On a mobile device (do we have a list of which we will test against?) if title is long then it responds gracefully, rather than spills out of the nav box.
* Does not break other patterns.
* HTML is well-formed.
* CSS is well-formed.

---

Responsible: Aaron
Tester: ?

**Comment by garethjmsaunders** [comment]
Carley: Example of the problem can be found on this page - https://www.st-andrews.ac.uk/students/robert-jones-scholarship-programme/

Lewis: A fix for this could be to increase the height overall of this pattern and center the titles and chevron vertically. This is a quick fix. It may be harder to only auto fix height for titles that wrap over two lines.

Aaron: Navboxes are overflowing when the title is too long on Mobile Devices.
Need:
* Design Input: How to solve the problem; Smaller text, larger container, etc.
* Development: Update the pattern library to distribute this fix

**Comment by Aarontlott** [comment]
Worked with Lewis to sort this. Decided that it was a one-off issue and we corrected it with specific CSS to fit just that page.
