### ISSUE TITLE
FIX Hero banner Photoshop template link broken

### ISSUE THREAD

**Issue by bambattajb** [standrewsdigital/digital-pattern-library#43]
After building `docs` and selecting section `Hero Banner` - `/pattern/docs/patterns/hero-banner/index.html`

**Hero banner Photoshop template hyperlink** is broken.

![screenshot from 2016-08-11 11-47-13](https://cloud.githubusercontent.com/assets/480898/17586388/5fb1f1b0-5fb9-11e6-8adf-83a5646cc147.png)

**Comment by Aarontlott** [comment]
Addressing this in issue: https://github.com/standrewsdigital/digital-pattern-library/issues/45 and addressing the hero banner at large

**Comment by Aarontlott** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;R1N2mAlr&#x2F;1009-3-create-content-type-hero-banner"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> (3) Create content type: hero banner</a>

**Comment by garethjmsaunders** [comment]
Action required is to add a link to the hero banner Photoshop template to this pattern.

**Comment by garethjmsaunders** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(14) Hero banner](https://trello.com/c/n53i5UBA/334-14-hero-banner)

**Comment by garethjmsaunders** [comment]
This has now been resolved in this pull request: https://github.com/standrewsdigital/digital-pattern-library/pull/92

The fix is now in the master branch, and will be pushed to www/dpl when v0.8.0 deploys on Friday 2 December.
