### ISSUE TITLE
FIX Hero banner: PS template and rules

### ISSUE THREAD

**Issue by Aarontlott** [standrewsdigital/digital-pattern-library#45]
Lewis to reassess the hero banner rules and examples, as well as add in the PS template for them

**Comment by garethjmsaunders** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;3cZ4JtEf&#x2F;255-hero-banner-ps-template-and-rules"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Hero banner: PS template and rules</a>

**Comment by garethjmsaunders** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hero banner](https://trello.com/c/n53i5UBA/334-hero-banner)

**Comment by garethjmsaunders** [comment]
This was fixed in this pull request.
