### ISSUE TITLE
FEAT (New pattern) Create new-pattern skeleton for DPL

### ISSUE THREAD

**Issue by garethjmsaunders** [standrewsdigital/digital-pattern-library#5]
### Create new pattern package

Creating a new pattern in the DPL is not a straight forward task. It contains multiple tasks which are complex and often prone to user error.

It would be really helpful to create a standalone pattern skeleton that compiles correctly but isn't used, that can be copied and edited as a basis for other new packages.

### Acceptance criteria

* Compiles correctly in Grunt
* Is standalone and does not compromise other patterns or the DPL as a whole
* Can be easily copied and edited

---

Responsible: Gareth
Tester: ?

**Comment by Aarontlott** [comment]
QA'd and merged. Does not show up in the DPL but is in the file structure. New people working on the DPL will be instructed to use this as a template.
