### ISSUE TITLE
MAINT (GitHub) Clean up redundant Git branches

### ISSUE THREAD

**Issue by garethjmsaunders** [standrewsdigital/digital-pattern-library#54]
There are a number of redundant and training branches in GitHub that should probably be removed,

**Comment by garethjmsaunders** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Clean up redundant Git branches](https://trello.com/c/mvYW6vDX/287-clean-up-redundant-git-branches)

**Comment by garethjmsaunders** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Clean up redundant Git branches](https://trello.com/c/mxGHe98R/364-clean-up-redundant-git-branches)

**Comment by Aarontlott** [comment]
This has been resolved.
