### ISSUE TITLE
FIX (navigation-bar) nav bar not working after resize

### ISSUE THREAD

**Issue by woodenbridge94** [standrewsdigital/digital-pattern-library#56]
After opening and closing the top navigation bar, the 'display: none' is not removed when the window is changed to desktop mode. So the navigation bar does not re-appear.

**Comment by Aarontlott** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Navigation bar resize issue](https://trello.com/c/RmKjqQ98/304-navigation-bar-resize-issue)

**Comment by garethjmsaunders** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Navigation bar](https://trello.com/c/c6ARyErH/343-navigation-bar)

**Comment by Aarontlott** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(16) Header](https://trello.com/c/LTH8F4WS/333-16-header)

**Comment by ds231** [comment]
Resolved with merge #173
