### ISSUE TITLE
FIX Secondary nav on Homepage prototype doesnt show which page is currently being viewed, and confusing on mobile

### ISSUE THREAD

**Issue by garethjmsaunders** [standrewsdigital/digital-pattern-library#61]
The secondary nav doesn’t use `.currentbranch0` to show which page is currently being viewed

**Also:**
When you are in About with a smaller screen and open both navigation accordions the colour to indicate the current section is the same light blue as that for the section navigation. This reduces the clarity about which section I'm currently in (simply from the navigation). 

**Remedy:** Could the current section colour be something that is not blue?  Could the primary navigation selected colour be red (or other) for accordion nav, and section navigation selected colour be St Andrews blue?

**Remedy:** Determine whether it should. This is a design decision but it would be beneficial IMHO to use this.

@Type: Design
@Reported_by: Gareth
@Pages_affected: All pages with secondary navigation bar
@Devices_affected: All

**Comment by garethjmsaunders** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Navigation bar](https://trello.com/c/c6ARyErH/343-3-navigation-bar)

**Comment by ds231** [comment]
Resolved with merge of #173
